services:
  reactolith.twig_extension:
    class: Reactolith\SymfonyBundle\Twig\ReactolithTwigExtension
    tags:
      - { name: twig.extension }

  Reactolith\SymfonyBundle\Form\Type\SwitchType:
    tags:
      - { name: form.type }
